### ISSUE TITLE
I have this Problem when Bob moves to the left 

### ISSUE THREAD

**Issue by rurikCL** [obviam/star-assault#5]
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 50
    at cl.compumat.emat3d.model.World.getDrawableBlocks(World.java:58)
    at cl.compumat.emat3d.view.WorldRenderer.drawBlocks(WorldRenderer.java:121)
    at cl.compumat.emat3d.view.WorldRenderer.render(WorldRenderer.java:112)
    at cl.compumat.emat3d.screens.GameScreen.render(GameScreen.java:36)
    at com.badlogic.gdx.Game.render(Game.java:46)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:202)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:110)

**Comment by tyler6699** [comment]
Does not see you have the most up-to-date code.

**Comment by rurikCL** [comment]
i've downloaded the part 6

**Comment by tyler6699** [comment]
You could put in a test to ensure you do not go out of bounds for the array:

this line: for (int row = y; row <= y2 && row < no_rows; row++) {

int no_rows = level.getBlocks()[0].length;
int no_cols = level.getBlocks().length ;

for (int col = x; col <= x2 && col < no_cols; col++) {
    for (int row = y; row <= y2 && row < no_rows; row++) {
        block = level.getBlocks()[col][row];
        if (block != null) {
            blocks.add(block);
        }
    }
}

**Comment by johnou** [comment]
Fixed here https://github.com/obviam/star-assault/pull/7.
